// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SonKhoatnhom4.Data;

#nullable disable

namespace SonKhoatnhom4.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221205190719_Create_Table_CategoryProduct")]
    partial class CreateTableCategoryProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("SonKhoatnhom4.Models.CategoryProduct", b =>
                {
                    b.Property<string>("MaHangHoa")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenHangHoa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Thongtinhanghoa")
                        .HasColumnType("TEXT");

                    b.HasKey("MaHangHoa");

                    b.ToTable("CategoryProduct");
                });

            modelBuilder.Entity("SonKhoatnhom4.Models.DanhsachNCC", b =>
                {
                    b.Property<string>("Mancc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diachi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sodienthoai")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tenncc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Mancc");

                    b.ToTable("DanhsachNCC");
                });

            modelBuilder.Entity("SonKhoatnhom4.Models.Danhsachkhachhang", b =>
                {
                    b.Property<string>("Makhachhang")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diachi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sodienthoai")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tenkhachhang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Makhachhang");

                    b.ToTable("Danhsachkhachhang");
                });

            modelBuilder.Entity("SonKhoatnhom4.Models.Danhsachnhanvien", b =>
                {
                    b.Property<string>("Manhanvien")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diachi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sodienthoai")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tennhanvien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Manhanvien");

                    b.ToTable("Danhsachnhanvien");
                });

            modelBuilder.Entity("SonKhoatnhom4.Models.ImportStorage", b =>
                {
                    b.Property<string>("MaNhapKho")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaHangHoa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mancc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayNhapKho")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoLuong")
                        .HasColumnType("TEXT");

                    b.HasKey("MaNhapKho");

                    b.HasIndex("MaHangHoa");

                    b.HasIndex("Mancc");

                    b.ToTable("ImportStorage");
                });

            modelBuilder.Entity("SonKhoatnhom4.Models.Warehouse", b =>
                {
                    b.Property<string>("MaHangHoa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mancc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenHangHoa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenncc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trangthai")
                        .HasColumnType("TEXT");

                    b.HasKey("MaHangHoa");

                    b.HasIndex("Mancc");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("SonKhoatnhom4.Models.ImportStorage", b =>
                {
                    b.HasOne("SonKhoatnhom4.Models.CategoryProduct", "CategoryProduct")
                        .WithMany()
                        .HasForeignKey("MaHangHoa");

                    b.HasOne("SonKhoatnhom4.Models.DanhsachNCC", "DanhsachNCC")
                        .WithMany()
                        .HasForeignKey("Mancc");

                    b.Navigation("CategoryProduct");

                    b.Navigation("DanhsachNCC");
                });

            modelBuilder.Entity("SonKhoatnhom4.Models.Warehouse", b =>
                {
                    b.HasOne("SonKhoatnhom4.Models.CategoryProduct", "CategoryProduct")
                        .WithMany()
                        .HasForeignKey("MaHangHoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SonKhoatnhom4.Models.DanhsachNCC", "DanhsachNCC")
                        .WithMany()
                        .HasForeignKey("Mancc");

                    b.Navigation("CategoryProduct");

                    b.Navigation("DanhsachNCC");
                });
#pragma warning restore 612, 618
        }
    }
}
